# Site settings
title: Arduino + Processing Lesson Plans
email: web.art@adriandiaz.ca
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "http://adriandgr.github.io/code"
url: "http://adriandgr.github.io/"
twitter_username: adgr72
github_username:  adriandgr

# Build settings
markdown: kramdown
permalink: pretty
