# Site settings
title: learn Arduino + Processing
email: web.art@adriandiaz.ca
description: "Programming Boot Camp by Nick Leowen and Adrian Diaz."
baseurl: "http://adriandgr.github.io/code"
url: "http://adriandgr.github.io/"
twitter_username: adgr72
github_username:  adriandgr

# Build settings
markdown: kramdown
permalink: pretty

authors:
  adrian:
    name: Adrian Diaz
    display_name: Adrian
    gravatar: 1092e44f33d0454dfb580e19f3687ce8
    email: web.art@adriandiaz.ca
    web: http://www.adriandiaz.ca/
    twitter: adgr72
    github: adriandgr
  nick:
    name: Nick Loewen
    display_name: Nick
    web: http://www.nloewen.com/
    github: nickloewen
