# Site settings
title: Learn Arduino + Processing
email: web.art@adriandiaz.ca
description: "Programming Boot Camp by Nick Leowen and Adrian Diaz."
baseurl: "http://adriandgr.github.io/code"
url: "http://adriandgr.github.io/"
twitter_username: adgr72
github_username:  adriandgr

# Build settings
markdown: kramdown
permalink: pretty
